build-aseprite:
    name: Build Aseprite
    needs: check-version
    if: ${{ needs.check-version.outputs.should_build == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Get Skia from cache
        id: skia-cache
        uses: actions/cache@v4
        with:
          path: skia
          key: skia-windows-cache

      - name: Download Skia if not in cache
        if: steps.skia-cache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          curl -o Skia-Windows-Release-X64.zip -L https://github.com/aseprite/skia/releases/download/m81-b607b32047/Skia-Windows-Release-X64.zip
          Expand-Archive Skia-Windows-Release-X64.zip -DestinationPath skia

      - name: Download Aseprite source
        shell: pwsh
        run: |
          curl -o Aseprite-source.zip -L ${{ needs.check-version.outputs.download_url }}
          Expand-Archive Aseprite-source.zip -DestinationPath aseprite
          New-Item -ItemType Directory -Force -Path aseprite\build

      - name: Run CMake and Ninja
        working-directory: aseprite/build
        shell: cmd
        run: |
          :: Use the modern VS 2022 path
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          
          :: Run CMake
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ^
                -DLAF_BACKEND=skia ^
                -DSKIA_DIR=../../skia ^
                -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 ^
                -G Ninja ..
          
          :: Run the actual build
          ninja aseprite

      - name: Create portable zip
        working-directory: aseprite/build/bin
        shell: pwsh
        run: |
          echo '# Portable' > aseprite.ini
          Compress-Archive -Path * -DestinationPath Aseprite-Windows.zip

      - name: Create Release and Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.check-version.outputs.latest_tag }}
        shell: pwsh
        run: |
          gh release create "$env:TAG" aseprite/build/bin/Aseprite-Windows.zip --title "Aseprite $env:TAG" --notes "Automated build of Aseprite $env:TAG"