name: Build and deploy Aseprite

on:
  push:
    branches:
      - master
  workflow_dispatch: # This adds the "Force Run" button in GitHub Actions

env:
  BUILD_TYPE: Release

jobs:
  build-aseprite:
    name: Build Aseprite
    runs-on: windows-latest
    steps:
      - name: Get latest version info
        id: version_info
        run: |
          data=$(curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest)
          LATEST_TAG=$(echo "${data}" | jq -r '.tag_name')
          DOWNLOAD_URL=$(echo "${data}" | jq -r '.assets[].browser_download_url')
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "download_url=${DOWNLOAD_URL}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get Skia from cache
        id: skia-cache
        uses: actions/cache@v4
        with:
          path: skia
          key: skia-windows-cache

      - name: Download Skia if not in cache
        if: steps.skia-cache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          curl -o Skia-Windows-Release-X64.zip -L https://github.com/aseprite/skia/releases/download/m81-b607b32047/Skia-Windows-Release-X64.zip
          Expand-Archive Skia-Windows-Release-X64.zip -DestinationPath skia

      - name: Download Aseprite source
        shell: pwsh
        run: |
          curl -o Aseprite-source.zip -L ${{ steps.version_info.outputs.download_url }}
          Expand-Archive Aseprite-source.zip -DestinationPath aseprite
          if (!(Test-Path aseprite\build)) { New-Item -ItemType Directory -Path aseprite\build }

      - name: Run CMake and Ninja
        working-directory: aseprite/build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DLAF_BACKEND=skia -DSKIA_DIR=../../skia -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 -G Ninja ..
          ninja aseprite

      - name: Create portable zip
        working-directory: aseprite/build/bin
        shell: pwsh
        run: |
          echo '# Portable' > aseprite.ini
          Compress-Archive -Path * -DestinationPath Aseprite-Windows.zip

      - name: Create Release and Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.version_info.outputs.latest_tag }}
        shell: pwsh
        run: |
          # The --clobber flag allows us to overwrite the release if it already exists
          gh release create "$env:TAG" aseprite/build/bin/Aseprite-Windows.zip --title "Aseprite $env:TAG" --notes "Automated build" --clobber